//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _05.CreateConsoleAppToConsumeService.StringCounterServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StringCounterServiceReference.IStringCounterService")]
    public interface IStringCounterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringCounterService/CountTimesFirstContainedInSecondString", ReplyAction="http://tempuri.org/IStringCounterService/CountTimesFirstContainedInSecondStringRe" +
            "sponse")]
        int CountTimesFirstContainedInSecondString(string first, string second);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringCounterService/CountTimesFirstContainedInSecondString", ReplyAction="http://tempuri.org/IStringCounterService/CountTimesFirstContainedInSecondStringRe" +
            "sponse")]
        System.Threading.Tasks.Task<int> CountTimesFirstContainedInSecondStringAsync(string first, string second);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStringCounterServiceChannel : _05.CreateConsoleAppToConsumeService.StringCounterServiceReference.IStringCounterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StringCounterServiceClient : System.ServiceModel.ClientBase<_05.CreateConsoleAppToConsumeService.StringCounterServiceReference.IStringCounterService>, _05.CreateConsoleAppToConsumeService.StringCounterServiceReference.IStringCounterService {
        
        public StringCounterServiceClient() {
        }
        
        public StringCounterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StringCounterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StringCounterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StringCounterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CountTimesFirstContainedInSecondString(string first, string second) {
            return base.Channel.CountTimesFirstContainedInSecondString(first, second);
        }
        
        public System.Threading.Tasks.Task<int> CountTimesFirstContainedInSecondStringAsync(string first, string second) {
            return base.Channel.CountTimesFirstContainedInSecondStringAsync(first, second);
        }
    }
}
