console.log("1. Assign all thе possible JavaScript literals to different variables.");
console.log('Boolean literals');
var boolTrue = true;
var boolFalse = false;
console.log(boolTrue);
console.log(boolFalse);
console.log('Integer literals');
var num = 5;
console.log(num);
num = -222;
console.log(num);
console.log('Floating-point literals');
num = 1.2;
console.log(num);
num = -1.2332;
console.log(num);
console.log('Object literals');
var phone = { make: "Apple", model: "IPhone" };
console.log(phone);
console.log(phone.make);
console.log(phone.model);
console.log('String literals');
var text = 'SomeString';
console.log(text);
text += text;
console.log(text);
console.log(" ");
console.log("2.Create a string variable with quoted text in it.");
text = "\"How you doin\'?\", Joey said.";
console.log(text);
console.log(" ");
console.log("3.Try typeof on all variables you created.");
console.log("On boolean type: " + typeof(boolFalse));
console.log("On number type: " + typeof(num));
console.log("On obj type: " + typeof(phone));
console.log("On string type: " + typeof (text));
console.log(" ");
console.log("4. Create null, undefined variables and try typeof on them.");
var nullVar = null;
var undefinedVar = undefined;
console.log("Null is " + typeof(nullVar));
console.log("Undefined is " + typeof(undefinedVar));
